### ISSUE TITLE
State of this project?

### ISSUE THREAD

**Issue by fvictorio** [OasisDEX/metamask-e2e#10]
This seems like a really cool and potentially useful project. But as far as I can tell, there's nothing published in npm. Are there plans to make this public?

Edit: I see that the puppeteer part of this projets *is* published, I was checking the cypress part.

**Comment by krzkaczor** [comment]
Thanks for interest in this project. Yes, puppeter part works and is used by Oasis. Note that there is a more community-driven project called [dappeteer](https://github.com/decentraland/dappeteer). 

Cypress part was an experiment which unfortunately didn't work out. It sort of works but randomly fails so we don't use it.
